### ISSUE TITLE
Copyright and License infringement

### ISSUE THREAD

**Issue by nicolaasuni** [milon/barcode#1]
I have noticed that this project is using source code copied from the project https://github.com/tecnickcom/TCPDF originally hosted at http://sourceforge.net/projects/tcpdf/ but all original notices about author, copyright and license were removed or replaced.

Apparently you forked or copied the code from another project that has been already shut down with a DMCA takedown notice.

You can compare the files yourself against TCPDF version 6.0.025 released 4 September 2013 (https://github.com/tecnickcom/TCPDF/tree/6.0.025):

In this project the following files appears to be almost verbatim copies of the original ones, with the exception of the legal notices removed (author, copyright and license):

* src/Milon/Barcode/Datamatrix.php (include/barcodes/datamatrix.php)
* src/Milon/Barcode/DNS1D.php (tcpdf_barcodes_1d.php)
* src/Milon/Barcode/DNS2D.php (tcpdf_barcodes_2d.php)
* src/Milon/Barcode/PDF417.php (include/barcodes/pdf417.php)
* src/Milon/Barcode/QRcode.php (include/barcodes/qrcode.php)

The original code is released under the GNU LGPLv3 license and copyrighted by Nicola Asuni - Tecnick.com LTD, but none of this information is present in the copied files.
https://github.com/tecnickcom/TCPDF/blob/6.0.025/LICENSE.TXT

The options to remedy the infringement are:

1. delete the project - this seems the best option as this project seems not adding any new functionality;
2. if the license is compatible with GNU-LGPLv3, replace the infringing files with the original ones, or reinstate all the original notices (author, copyright, license);
3. delete the infringing files and use the new external library https://github.com/tecnickcom/tc-lib-barcode (originally based on the same code).

An immediate action is required as this infringement is serious.

**Comment by milon** [comment]
Thanks @nicolaasuni 

Actually I forked it from https://github.com/dineshrabara/barcode and I don't know that it was using your code. I am going to change the readme file, and the license agreement that is competable with your project. 

I am in a vacation, our 2nd biggest religious festival is tomorrow. I will be very busy. I will change the necessary changes within 2-3 days. Hope you understand. Thanks again.

**Comment by milon** [comment]
Hey @nicolaasuni, I just changed the license and the readme file of this package. Hope it is okay, if not feel free to knock me, I will change it. Thanks.

**Comment by nicolaasuni** [comment]
You have to reinstate the original headers with copyright notices in each file.

**Comment by milon** [comment]
Ok, I am going to fix that today's night.  
thanks for your reply.

**Comment by milon** [comment]
@nicolaasuni, I have changed the headers of the files with the copyright notice. Hope its ok now. If it is, then please inform me. I will close the issue.
