### ISSUE TITLE
Array and string offset access syntax with curly braces is deprecated, php74,  milon/barcode: "^6.0"

### ISSUE THREAD

**Issue by violentzani** [milon/barcode#111]
Package Version "milon/barcode": "^6.0", 
Error Location: \vendor\milon\barcode\src\Milon\Barcode\DNS1D.php  
Error Message: Array and string offset access syntax with curly braces is deprecated 
Line Error: 560  
Error Code: $char = $code{$i};
Solution: $char = $code[$i];
PHP Version Intented: php74

**Comment by milon** [comment]
Thanks for reporting. just pushed a fix. Use tag `6.0.3` or later.

**Comment by najathi** [comment]
Thanks for updating the package

`composer require milon/barcode:^6.0`
