### ISSUE TITLE
Extra number in results

### ISSUE THREAD

**Issue by robertnicjoo** [milon/barcode#112]
I have barcode data in database like `qewf` and it print in my blade like:

![Screenshot(3)](https://user-images.githubusercontent.com/8672823/91166965-5d05d880-e6fd-11ea-9b13-e876e63f0a9f.png)

So far everything looks good,

But when i try to read this barcode I get `qewf1` where this `1` came from?

![Screenshot(4)](https://user-images.githubusercontent.com/8672823/91167067-8888c300-e6fd-11ea-9c1e-c467c2bb0a92.png)

# code

```php
<img src="data:image/png;base64,{!! \DNS1D::getBarcodePNG($product->barcode, 'C39+',1,50,array(1,1,1),true) !!}" alt="barcode" />
```
Any idea?

**Comment by ysfkaya** [comment]
I have that same problem. It put the letter "H" at the end

**Comment by ysfkaya** [comment]
I have solved the problem. I was changed barcode type to `C128` then it worked.

**Comment by robertnicjoo** [comment]
> 
> 
> I have solved the problem. I was changed barcode type to `C128` then it worked.

Thank you that worked
