### ISSUE TITLE
Make default storage path to storage_path('cache')

### ISSUE THREAD

**Issue by ank91** [milon/barcode#12]
Hi,
First; thanks for restoring ```dinesh/barcode``` repo.
Hope DMCA wont delete this one.

Here is the actual issue :
Your readme.md file says that -

>Make sure you have write permission to the storage path. By default it sets to /storage folder.

while [config.php](https://github.com/milon/barcode/blob/master/src%2Fconfig%2Fconfig.php#L4) file says it is ```public``` folder.

```php
return [
    'store_path' => public_path("/"),
];
```

It should be like this -
```php
return [
    'store_path' => storage_path("cache"),
];

```
I believe this the folder where barcodes will be stored temporary.
FYI: I am using this one on Laravel 4.2.

What your thoughts on this .

**Comment by milon** [comment]
I don't think it will get DMCA notice. I take permission from the original author. :)

I am at work. will do when I am at home. Thanks.

**Comment by wallacemaxters** [comment]
I have the same problem.
The classes that use the `Config::get('barcode.storage_path') should use
`Config::get('barcode::config.store path')`.

Why, doing in this form, the `php artisan config:publish milon/barcode --env=local` command doesn't work as expected.

In my tests on Laravel 4.2, when running `php artisan tinker --env=local`, the results are as following:

```bash
> Config::get('barcode.storage_path');
NULL
> Config::get('barcode::config.storage_path');

'/var/www/my_app/public/barcode/'
```

**Comment by wallacemaxters** [comment]
In [this pull](https://github.com/milon/barcode/pull/14) request I fix this
