### ISSUE TITLE
I have a error. Please can you help me? pls pls.

### ISSUE THREAD

**Issue by costinbogdan** [milon/barcode#18]
Non-static method Milon\Barcode\DNS1D::getBarcodeHTML() should not be called statically, assuming $this from incompatible context

My code is this 
 echo DNS1D::getBarcodeHTML("4445645656", "C128");

If I change with this 

echo DNS1D->getBarcodeHTML("4445645656", "C128");

gives another error
syntax error, unexpected '->' (T_OBJECT_OPERATOR), expecting ',' or ';'

What can I do? Please somebody help me

I am using laravel version 5.1

**Comment by wisosonic** [comment]
you are trying to generate this barcode in a blade View?

**Comment by wisosonic** [comment]
try to generate it in a controller then pass it to your view file. Here is an example :

`<?php namespace App ;

use Illuminate\Database\Eloquent\Model;
use DNS1D;
use Picqer;

class Barcode extends Model {

        public static function codeToBarcode ($code) 
        {
                $generator = new Picqer\Barcode\BarcodeGeneratorPNG();
                $barcode = DNS1D::getBarcodeHTML("3358027510079", "EAN13",3,80, 'black') ;
                return view('barcode', ['barcode' => $barcode]) ;
        }
`
}

**Comment by lalustineburra** [comment]
Class 'Picqer\Barcode\BarcodeGeneratorPNG' not found..need help

**Comment by wisosonic** [comment]
actually its my mistake.. no need to add that line !

`public static function codeToBarcode ($code) 
        {
                $barcode = DNS1D::getBarcodeHTML("3358027510079", "EAN13",3,80, 'black') ;
                return view('barcode', ['barcode' => $barcode]) ;
        }
`
