### ISSUE TITLE
Class 'DNS1D' not found

### ISSUE THREAD

**Issue by williamavelino** [milon/barcode#19]
Segui os passos recomendados porém esta com esse erro, Class 'DNS1D' not found.

Versão Laravel 5.1.40 
composer.json
"laravel/framework": "5.1.*",
"milon/barcode": "^5.1"

**Comment by milon** [comment]
try to import this line at the top of the code-
```
use Milon\Barcode\DNS1D;
```

**Comment by williamavelino** [comment]
I'm using the view.
{{ DNS1D::getBarcodeHTML("4445645656", "PHARMA2T") }}

**Comment by williamavelino** [comment]
I managed to solve. Not publishing.
commands:
      php artisan config: clear 
      php artisan vendor: publish --force
Result
     Publishing is complete tag []!
