### ISSUE TITLE
Class 'Milon\Barcode\BarcodeServiceProvider::class' not found - Laravel 4

### ISSUE THREAD

**Issue by shawindershingora** [milon/barcode#20]
Hi everyone,
we have installed milon barcode on local server successfully. but when we go on live server we got "Class 'Milon\Barcode\BarcodeServiceProvider::class' not found" Error 

i have checked vendor directory also everything is fine there all files are placed properly

please refer to below link for screen shot 
Thanks in Advance
![image](https://cloud.githubusercontent.com/assets/18567753/17125793/52ead4c6-5314-11e6-984f-462a353d686e.png)

**Comment by milon** [comment]
@shawindershingora, what is the version of php in your server?

**Comment by andrewtweber** [comment]
Sounds like you have `Milon\Barcode\BarcodeServiceProvider::class` in quotes.

**GOOD**

```php
'provider' = [
     Milon\Barcode\BarcodeServiceProvider::class,
];
```

**BAD**

```php
'providers' = [
    "Milon\Barcode\BarcodeServiceProvider::class",
];
```

**Comment by ViktorPerezMoya** [comment]
I have the same problem. On my local computer it works correctly, but when I install it on the server I get the same error.
