### ISSUE TITLE
DNS1D::getBarcodeHTML() error

### ISSUE THREAD

**Issue by infernobass7** [milon/barcode#21]
I have been fighting with this package for a couple hours now trying to find a way to get it to function properly. I have used the way defined in the documentation as well as using call_user_func function. The closest I have to it working is using call_user_func, which puts out a white blank screen no barcode. Any help on this issue would be great.

Controller Code:
```
return view('modules.toolshop.sheet')->with([
			'log' => $transfer,
			'barcode' => '<img src="data:image/png;base64,' . call_user_func_array([new DNS1D(), 'getBarcodePNG'], ["10-057-00-000", "C39"])
		]);
```

View Code:
```
<?php echo $barcode;?>
{!! dd($barcode) !!}
```

**Comment by infernobass7** [comment]
Using dd() it gives a whole bunch of code but if I remove it there is nothing on the page.

**Comment by infernobass7** [comment]
In the example i provided above i missed a section 
```
. '" alt="barcode" />'
```
that caused it not to render. However, if i use it as a static call, it throws an error. I would rather use a static call.

**Comment by milon** [comment]
why are you using `dd()` for this? use echo or print.
