### ISSUE TITLE
Checksum Error

### ISSUE THREAD

**Issue by petyots** [milon/barcode#24]
Hello, if I follow the instructions from https://tcpdf.org/ how to generate barcode with checksum the code returns this error

```
ErrorException in DNS1D.php line 171:
imagecreate(): Invalid image dimensions 

DNS1D::getBarcodePNG($order->id, "CODABAR+") !!}
````

The plus sign is to issue checksum bellow the barcode but it's not working. Without the plus sign everything is fine but I need the checksum. Thanks in advance

**Comment by alesf** [comment]
The CODABAR+ option does not exist in library.

Other variants have checksums though:
C39+ // CODE 39 with checksum
C39E+ // CODE 39 EXTENDED + CHECKSUM
S25+ // Standard 2 of 5 + CHECKSUM
I25+ // Interleaved 2 of 5 + CHECKSUM
MSI+ // MSI + CHECKSUM (modulo 11)
