### ISSUE TITLE
PHP Fatal error: Class 'Config' not found

### ISSUE THREAD

**Issue by junereycasuga** [milon/barcode#25]
Using Lumen Framework 5.3, I get the following error:
`PHP Fatal error: Class 'Config' not found in DNS2D.php`
when creating a qr code image by using:
```
$qr = new DNS2D();
$qr->getBarcodePngPath('abc123', 'QRCODE');
```

This can be fixed by using `app('config')->get()` instead of `\Config::get()`

**Comment by milon** [comment]
Thanks. @junereycasuga 

I fixed it. Use tag 5.3.0 for lumen 5.3
