### ISSUE TITLE
UPCE barcode gives different value

### ISSUE THREAD

**Issue by junereycasuga** [milon/barcode#27]
I'm trying to create a UPCE barcode using `echo DNS1D::getBarcodeHTML('123456', 'UPCE');` but when I scan the barcode, it gives me a different value

**Comment by milon** [comment]
thanks

**Comment by junereycasuga** [comment]
@milon when are you going to create a version for this fix?

**Comment by milon** [comment]
I just tag your fix with 5.3.2
