### ISSUE TITLE
No barcode in Laravel 5*

### ISSUE THREAD

**Issue by saaiful** [milon/barcode#3]
No barcode in Laravel 5*
Only HTML Version Works
PNG : 

data:image/png,iVBORw0KGgoAAAANSUhEUgAAAQAAAAAeAQMAAAD5F1J6AAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAACJJREFUKJFjOHD+/Jkz/GiY588fEAbJMYwqGFUwqmBoKgAAqn+OB+RXYEAAAAAASUVORK5CYII=

It's invalid

SVG Works

**Comment by eduavila** [comment]
Tries to put with base64 as in the example below. Here it is working.
```'<img src="data:image/png;base64,' .DNS1D::getBarcodePNG("4", "C39") . '" alt="barcode"   />'```

**Comment by saaiful** [comment]
hum seems like i missed base64 part :P
