### ISSUE TITLE
production problems

### ISSUE THREAD

**Issue by grimpa** [milon/barcode#30]
Hi,

I'm using Laravel 5.2 and I've the follow html:

```<img class="barcode" src="data:image/png;base64, {{ DNS1D::getBarcodePNG($id, 'C39')  }}"/>```

In my development environment works like a charm! But in production environment I having a problem. The base64 isn't generated, for example:

##DEV:
```<img class="barcode" src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAGAAAAAeAQMAAADpfonKAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAAlwSFlzAAAOxAAADsQBlSsOGwAAABhJREFUGJVjOHD+/JkzPH/+gGiGUc7AcADTphJI4YlzuAAAAABJRU5ErkJggg==">```

<img width="146" alt="screen shot 2016-10-26 at 23 39 41" src="https://cloud.githubusercontent.com/assets/594651/19751090/7de6c4f0-9bd5-11e6-89ca-c29edfa8b929.png">

##PROD:
```<img class="barcode" src="data:image/png;base64, ">```

<img width="124" alt="screen shot 2016-10-26 at 23 40 26" src="https://cloud.githubusercontent.com/assets/594651/19751097/993948b8-9bd5-11e6-83f3-8d88ec1db85a.png">

Anybody help me?
Thanks.

**Comment by milon** [comment]
What is your OS on production server, I assume ubuntu. This package relies on php-gd library. so, please install it, and check it again.

**Comment by grimpa** [comment]
perfect! Thanks!

**Comment by henrydyx** [comment]
i already install php-gd library but still not working

**Comment by RafyMrX** [comment]
im using Laravel ^9, i got same problem, 
`<img src="data:image/png;base64,{{DNS2D::getBarcodePNG( $produk->barcode,'PDF417')}}"`

im using windows 11, previously that code working fine, but now i got problem
