### ISSUE TITLE
print is not viewing the barcode.

### ISSUE THREAD

**Issue by zahangir015** [milon/barcode#34]
I have tried to print the barcode but failed. I have tried with browser option ctrl+p and with datatable print option.

**Comment by milon** [comment]
Maybe it is data table's issue rather than barcode's issue. You should be more precise about your problem. Try to post the detail and code snippets that it would be much easier to answer.

**Comment by zahangir015** [comment]
This is my controller method through which i have passed the DNS1D $dns1d, DNS2D $dns2d objects to view-
public function view(DNS1D $dns1d, DNS2D $dns2d, Client $client) {

        $title = 'Client Details';

        return view('client.client_details', compact('title', 'client', 'dns1d', 'dns2d'));
    }

And In view I have used these object to show the barcodes here is the view -

<tr>
                                <td><strong>Name :</strong> {{ $client->name }}</td>
                                <td><div style="padding: 25px;"><?php echo $dns1d->getBarcodeHTML($client->name, "C39",1.8,60); ?></div></td>
                            </tr>
                            <tr>
                                <td><strong>Date Of Birth :</strong> {{ date('d-M-Y', strtotime($client->birth_date)) }}</td>
                                <td><div style="padding: 25px;"><?php echo $dns1d->getBarcodeHTML($client->birth_date, "C39",1.8,60); ?></div></td>
                            </tr>
                            <tr>
                                <td><strong>Phone :</strong> {{ $client->phone }}</td>
                                <td><div style="padding: 25px;"><?php echo $dns1d->getBarcodeHTML($client->phone, "C39",1.8,60); ?></div></td>
                            </tr>
                            <tr>
                                <td><strong>National ID Number :</strong> {{ $client->n_id }}</td>
                                <td><div style="padding: 25px;"><?php echo $dns1d->getBarcodeHTML($client->n_id, "C39",1.8,60); ?></div></td>
                            </tr>
                            <tr>
                                <td><strong>Passport :</strong> {{ $client->passport }}</td>
                                <td><div style="padding: 25px;"><?php echo $dns1d->getBarcodeHTML($client->passport, "C39",1.8,60); ?></div></td>
                            </tr>

Its viewing perfectly but at the time of printing bracodes are not appearing.

**Comment by milon** [comment]
The problem is with your browser. Try to check the settings of your browser. As it is showed correctly on the browser, it's not an issue with this package. This package can't do anything with the print.

**Comment by zahangir015** [comment]
There is no problem with print option in browsers I am hundred percent sure. Check your package.

**Comment by milon** [comment]
@zahangir015 I used it in several projects and it works fine in all of those cases. So, it is not my headache to solve this. I can't even regenerate the bug.

**Comment by zahangir015** [comment]
I have found a solution that is for print barcode one need to generate the barcode using getBarcodePNG method.

**Comment by engsamar** [comment]
@zahangir015  Are u print barcode with zebra printer

**Comment by sabaoonbedar** [comment]
use like this     <div>{!! DNS1D::getBarcodeSVG('897879', 'C39',0.9,50,'black',true) !!}</div>

**Comment by markus-javier** [comment]
enable background graphics in the browsers print option

**Comment by lilraz70** [comment]
> J'ai trouvé une solution qui permet d'imprimer un code-barres, il faut générer le code-barres à l'aide de la méthode getBarcodePNG.

merci
