### ISSUE TITLE
That would be a typo?

### ISSUE THREAD

**Issue by wallacemaxters** [milon/barcode#37]
The class `DNS1D` has a line with follow code:

`$bgcol = new \imagickpixel('rgb(255,255,255');`

That would be a typo?

Would that be a typo? Seems the correct way should look like this: 

`$bgcol = new \imagickpixel('rgb(255,255,255)');`

The line:

https://github.com/milon/barcode/blob/master/src/Milon/Barcode/DNS1D.php#L177

**Comment by milon** [comment]
@wallacemaxters thanks man. Fixing it.
