### ISSUE TITLE
Barcode displaying as blocks instead of barcode

### ISSUE THREAD

**Issue by infernobass7** [milon/barcode#38]
I have been using this package to generate barcodes for various pieces in my application. Yesterday I had to make updates to the linux server that the application is running on now the barcodes come out as blocks instead of like a barcode.  I have added photograph to show what I mean. I have not been able to reproduce this issue in my local development.

What it looks like now:
![barcode_as_blocks](https://cloud.githubusercontent.com/assets/6399755/23756016/5534f1a0-04b0-11e7-9d3e-c325d12c9ee1.JPG)

What it used to look like:
![barcode](https://cloud.githubusercontent.com/assets/6399755/23756113/a206401a-04b0-11e7-85b6-57c40ef6727b.JPG)

**Comment by milon** [comment]
your server config?

**Comment by infernobass7** [comment]
The server is running Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-66-generic x86_64)

**Comment by infernobass7** [comment]
@milon have you had any progress with this issue?

**Comment by milon** [comment]
@infernobass7 I tried to regenerate the issue in my machine but failed. I even tried the same OS you tried in VM, but it works perfectly. I couldn't find any reason. :(

**Comment by infernobass7** [comment]
That is what I was afraid of because I don't know what changed to cause the issue.

**Comment by infernobass7** [comment]
I think it was some kind of fluke. Reinstalled in separate directory and it worked perfectly fine.

**Comment by infernobass7** [comment]
It appears to be an issue with getBarcodePNG. Below is the line that I was using:
```
'<img src="data:image/png;base64,' . call_user_func_array([new DNS1D(), 'getBarcodePNG'], [str_replace("*", "-", $id), "C39", 1]) . '" alt="barcode" />'
```
