### ISSUE TITLE
Fatal error: Using $this when not in object context in /vendor/milon/barcode/src/Milon/Barcode/DNS2D.php on line 96

### ISSUE THREAD

**Issue by mozgbrasil** [milon/barcode#42]
Hello

Good Morning

View the images that appear in the attempt to use the library

Can you tell me how to use it?

![captura de tela de 2017-04-05 12-06-51](https://cloud.githubusercontent.com/assets/17202780/24712225/a6830a3a-19f8-11e7-8f77-a1419422f1e0.png)
![captura de tela de 2017-04-05 12-08-46](https://cloud.githubusercontent.com/assets/17202780/24712223/a67d14fe-19f8-11e7-8c8d-5cf40744b13e.png)
![captura de tela de 2017-04-05 12-08-53](https://cloud.githubusercontent.com/assets/17202780/24712224/a67fb51a-19f8-11e7-8154-afdeb6b88395.png)

**Comment by milon** [comment]
you should use it like this-
```
require(__DIR__.'/vendor/autoload.php');

use \Milon\Barcode\DNS2D;

$d = new DNS2D();
$d->setStorPath(__DIR__."/cache/");
echo $d->getBarcodeSVG("4445645656", "DATAMATRIX");
```
