### ISSUE TITLE
Getting false on getBarcodePNG

### ISSUE THREAD

**Issue by antonioreyna** [milon/barcode#47]
I am trying to do this: 

```
DNS1D::getBarcodePNG("1234", "C128C")
```

and it does nothing, it works with `getBarcodeHTML`

**Comment by antonioreyna** [comment]
it was GD lib thanks!

**Comment by juanantoniodamianv** [comment]
@antonioreyna I got the same response in Ubuntu 16.4, I need to install GD lib separated?
