### ISSUE TITLE
Show the bar code figure

### ISSUE THREAD

**Issue by amirgee007** [milon/barcode#48]
hi i want to show the barcode as well as its figure at below the barcode can you please tell me how to do this? Thanks

https://www.google.com.pk/search?q=barcode&tbm=isch&source=lnms&sa=X&ved=0ahUKEwiAzdS_o7nUAhWLLY8KHaw6DjsQ_AUIBigB&biw=1366&bih=589#imgrc=97WsJeR-1b5rUM:

like this image 
![git](https://user-images.githubusercontent.com/16411441/27056654-67105dd8-4fe2-11e7-8a97-5a09e4e0b543.PNG)

**Comment by maosalah** [comment]
you can try   
#51
