### ISSUE TITLE
Missing argument 3 for Milon\Barcode\WrongCheckDigitException::__construct()

### ISSUE THREAD

**Issue by kotenarok** [milon/barcode#54]
Missing argument 3 for Milon\Barcode\WrongCheckDigitException::__construct(), called in /vendor/milon/barcode/src/Milon/Barcode/DNS1D.php on line 1427 and defined

Code DNS1D.php line 1427
`throw new \Milon\Barcode\WrongCheckDigitException($r, intval($code{$data_len}));`
which has 2 arguments

But your class WrongCheckDigitException
`public function __construct($actual = NULL, $expected = NULL, $code, \Exception $previous = NULL)`
require argument 3

**Comment by dannyreinders** [comment]
Same issue.

**Comment by victorhugorch** [comment]
Same issue.

**Comment by edsonpro** [comment]
Same issue.

**Comment by nicelife90** [comment]
Same issue.

**Comment by gitdward** [comment]
Same issue.

**Comment by alira4d** [comment]
same issue

**Comment by MochIchsanMaulana** [comment]
same issue.

**Comment by rashed50702** [comment]
Same Issue
