### ISSUE TITLE
Permission Denied to unlink png file

### ISSUE THREAD

**Issue by demobiel** [milon/barcode#57]
Hi

thanks for this library, but I am a little lost on an error I get.
I got it all working on my local environment, but when I push it to prod (on Ubuntu 16.04.3 hosted by DigitalOcean), I get an error during creation of the Barcode.

The error I get is : 
ErrorException in DNS1D.php line 2371:
unlink(4445645656.png): Permission denied

I guess this has to do with folder permissions, but I don't see where the library is trying to save the file and why it is not allowed to delete it.

Do you have any advice?

Thanks!

Andries

**Comment by milon** [comment]
check the permission of your server's folder, where you actually store it. It has nothing to do with this package.
