### ISSUE TITLE
Make compatible to Laravel 5.2 (change bindShared() to singleton() in BarcodeServiceProvider

### ISSUE THREAD

**Issue by andreasba** [milon/barcode#6]
Illuminate\Foundation\Application::bindShared() is depricated as per Laravel 5.2 and should be changed to singleton() otherwise the following error is thrown:

Error Output: PHP Fatal error:  Call to undefined method Illuminate\Foundation\Application::bindShared() in /xxxvendor/milon/barcode/src/Milon/Barcode/BarcodeServiceProvider.php on line 33

Thanks
Andreas

**Comment by milon** [comment]
Thanks for reporting @andreasba  
i fixed it, check it out.

**Comment by andreasba** [comment]
Thanks :) However, a composer update doesnt find the package after updating it to ~2.0 in the .json file - also https://packagist.org/packages/milon/barcode doesnt show it as released?

Thanks
Andreas

**Comment by milon** [comment]
It seems github hook doesn't work for some reason. I manually push it, now you could use it.  
Thanks again, @andreasba
