### ISSUE TITLE
URGENT strange characters while reading DATAMATRIX barcode

### ISSUE THREAD

**Issue by anasred** [milon/barcode#60]
if I need to generate a barcode for the following code:
M-CNS301-1-4-86104-851-2018-01-15-2018-01-15-000001-0000000000

It's generated. but once you scan it you got this:
M-CNS301-1-4k-"LL2;IM":V$2:NK)D.%)L.#": K(JB!B:B (JB (D>82

Im using it like this in my view
{!! \DNS2D::getBarcodeSVG($barcode->barcode, "DATAMATRIX") !!}

I have over 100 barcodes and all of them once scanned they produce the same code except these that starts with "M-CNS301" Why??

**Comment by anasred** [comment]
I solve the issue temporarily using strtolower() on the code like so:
{!! \DNS2D::getBarcodeSVG(strtolower($barcode->barcode), "DATAMATRIX") !!}

But I'm afraid your library bight produce new error in the future? or maybe it's my fault somewhere!!

**Comment by hitwork** [comment]
I have the same Problem, this code produces broken Datamatrix
3ZDM;D5337320520201B;DEV-50209/1002 ACP-MK;
with strtolower() it works perfectly

**Comment by hitwork** [comment]
Fail: 3ZDM;D5337320520201B;DEV-50209/1002 ACP-MK;
Works: 3ZDM;D5337320520201B;DEV-50209/1002 ACp-MK;

But it is all too random to use this module in production currently...
