### ISSUE TITLE
EAN Barcode numbers at the bottom

### ISSUE THREAD

**Issue by edwinmugendi** [milon/barcode#67]
Thanks for your great library. 

How do we display the numbers below the barcode?

Which configuration do we set? 
![barcode](https://user-images.githubusercontent.com/1918024/44096282-960a1960-9fe3-11e8-83df-42f1f073db38.png)

Thanks in advance,
Edwin

**Comment by David91vlc** [comment]
Hello, i have the same problem. Do you know the answer?

Regards

**Comment by OAmor** [comment]
i got the same problem , so i did it manually , i know that is a bad practice but it better than nothing.
this is how the code look like 
`<div class="barcode-item">
        <?php echo DNS1D::getBarcodeHTML($barcode, "EAN13"); ?>
        <span style="margin-left: 15%">{{$barcode}}</span>
    </div>`
if there is a better solution let us know :)

**Comment by badrul1329** [comment]
it would be better if it has the options to add header text and footer text, may be it will be the bar code or any other given text.

**Comment by saaiful** [comment]
This package is a fork (part) of TCPDF's barcode lib. Check out all the examples for 1D barcodes https://tcpdf.org/examples/example_027/. The style above is known as "Non Flat", and TCPDF's Lib doesn't have support for that.
