### ISSUE TITLE
How to create an EAN without control digit?

### ISSUE THREAD

**Issue by realtebo** [milon/barcode#74]
I need to transform to EAN ( yes, UNVALID codes...) some arbitrary number sequences.

In short, I need to create, for example, the ean-8 of `5551147` WITHOUT adding the checkdigit at the end, or, seen from another perspective, generate the ean-8 '0551147' even if ean check digit is NOT valid

Is there any way to realize this?

**Comment by milon** [comment]
I am not familiar with the situation.
