### ISSUE TITLE
Documentation Is Lacking

### ISSUE THREAD

**Issue by thecodecafe** [milon/barcode#82]
Hello, please I just wanted to leave this here, the documentation for this package is really lacking it assumes the person using the package already know exactly what they are passing to the methods on the generator classes.
E.g
```
echo DNS1D::getBarcodeSVG("4445645656", "PHARMA2T", 3, 33);
```
What are **"4445645656", "PHARMA2T", 3, and 33** in arguments list in this code snippet? There seems to be no description telling the developer what each argument represents, I personally have no clue what they are so I don't even know what I am passing there. Making this package difficult to use, will be better if you had a section on the read me that explains this.

**Comment by milon** [comment]
@thecodecafe thanks for your comment. Feel free to add documentation and make PR.
