### ISSUE TITLE
How to generate fixed sized barcode ?

### ISSUE THREAD

**Issue by csesumonpro** [milon/barcode#93]
## How to generate a fixed-sized barcode?

When I increase the size of code it will automatically increase the width of the barcode.

=> Long code 
![image](https://user-images.githubusercontent.com/29582239/70933605-7d599f80-2066-11ea-8c5c-89030e603f70.png)

=> short code
![image](https://user-images.githubusercontent.com/29582239/70933707-a4b06c80-2066-11ea-8010-ea4e8b5254a4.png)

**Comment by hieuna** [comment]
Hello, You can use example here:
<div class="container text-center" style="border: 1px solid #a1a1a1;padding: 15px;width: 200px;">
	<img src="data:image/png;base64,{{DNS1D::getBarcodePNG('A209342', 'C39',1,50,array(0,0,0), true)}}" alt="barcode" style="width: 100%"/>
</div>

**Comment by prabodhana** [comment]
I there any solution for this?

**Comment by e-hop** [comment]
+1

**Comment by 6miramira** [comment]
+1

**Comment by milon** [comment]
this is not possible, this is not how barcode works. If you have a long code, the barcode is going to be long.
